version: '3'

services:
  web:
    build: .
    links:
      - db:db
    command: /bin/sh web-init.sh
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
    depends_on:
      - db
    networks:
      - djangonetwork
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
    networks:
      - djangonetwork

networks:
      djangonetwork:
          driver: bridge